/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type ChatBubble = {
  _id: string;
  _type: 'chatBubble';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  messages?: Array<{
    inbound?: string;
    outbound?: string;
    _type: 'message';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: 'main' | 'company';
  seo?: Seo;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type App = {
  _id: string;
  _type: 'app';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
  subtitle?: string;
  excerpt?: string;
  body?: BlockContent;
  seo?: Seo;
  mainImage?: ImageWithAlt;
  type?:
    | 'health-care'
    | 'creative-and-media'
    | 'food-and-hospitality'
    | 'retail-and-commerce';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Capability = {
  _id: string;
  _type: 'capability';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  value?: number;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  contents?: Array<{
    title?: string;
    body?: string;
    _type: 'content';
    _key: string;
  }>;
};

export type CaseStudy = {
  _id: string;
  _type: 'caseStudy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: string;
  mainImage?: ImageWithAlt;
  startedAt?: string;
  endedAt?: string;
  excerpt?: string;
  body?: BlockContent;
  seo?: Seo;
  previewUrl?: string;
};

export type ServiceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
};

export type Subscription = {
  _id: string;
  _type: 'subscription';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  pricePerMonth?: number;
  type?: ServiceReference;
  excerpt?: string;
  inclusives?: Array<{
    title?: string;
    body?: string;
    _type: 'feature';
    _key: string;
  }>;
  exclusives?: Array<{
    title?: string;
    body?: string;
    _type: 'feature';
    _key: string;
  }>;
  seo?: Seo;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  subtitle?: string;
  excerpt?: string;
  body?: BlockContent;
  mainImage?: ImageWithAlt;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  seo?: Seo;
  navLinks?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavDropdown)
  >;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerText?: string;
  contactInfo?: {
    street?: string;
    zip?: string;
    city?: string;
    state?: string;
    email?: string;
    country?: string;
  };
};

export type VideoEmbedded = {
  _type: 'videoEmbedded';
  label?: string;
  videoId?: string;
  caption?: string;
};

export type FooterColumn = {
  _type: 'footerColumn';
  title?: string;
  links?: Array<{
    label?: string;
    href?: string;
    _type: 'link';
    _key: string;
  }>;
};

export type NavDropdown = {
  _type: 'navDropdown';
  label?: string;
  href?: string;
  dropdownLinks?: Array<{
    label?: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: 'dropdownGroup';
    _key: string;
  }>;
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  href?: string;
  isButton?: boolean;
  isExternal?: boolean;
};

export type Faq = {
  _type: 'faq';
  title?: string;
  body?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: string;
  url?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ChatBubble
  | Slug
  | Page
  | BlockContent
  | Seo
  | App
  | SanityImageAssetReference
  | ImageWithAlt
  | Capability
  | Faqs
  | CaseStudy
  | ServiceReference
  | Subscription
  | Service
  | SiteSettings
  | VideoEmbedded
  | FooterColumn
  | NavDropdown
  | NavLink
  | Faq
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/query.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == 'siteSettings'][0]{  navLinks[]{    _key,    _type,    href,    label,    isButton,    isExternal,    label,    dropdownLinks[]{      _key,      label,      links[]{        _key,        _type,        href,        label,        isButton,        isExternal      }    }  }}
export type NAVIGATION_QUERY_RESULT = {
  navLinks: Array<
    | {
        _key: string;
        _type: 'navDropdown';
        href: string | null;
        label: string | null;
        isButton: null;
        isExternal: null;
        dropdownLinks: Array<{
          _key: string;
          label: string | null;
          links: Array<{
            _key: string;
            _type: 'navLink';
            href: string | null;
            label: string | null;
            isButton: boolean | null;
            isExternal: boolean | null;
          }> | null;
        }> | null;
      }
    | {
        _key: string;
        _type: 'navLink';
        href: string | null;
        label: string | null;
        isButton: boolean | null;
        isExternal: boolean | null;
        dropdownLinks: null;
      }
  > | null;
} | null;

// Source: src/sanity/lib/query.ts
// Variable: FOOTER_QUERY
// Query: *[_type == 'siteSettings'][0]{  "columns": footerColumns[]{    _key,    title,    links[]{      _key,      href,      label    }  },  "text": footerText,  "street": contactInfo.street,  "zip": contactInfo.zip,  "city": contactInfo.city,  "state": contactInfo.state,  "email": contactInfo.email,  "country": contactInfo.country,  "socialLinks": socialLinks[]}
export type FOOTER_QUERY_RESULT = {
  columns: Array<{
    _key: string;
    title: string | null;
    links: Array<{
      _key: string;
      href: string | null;
      label: string | null;
    }> | null;
  }> | null;
  text: string | null;
  street: string | null;
  zip: string | null;
  city: string | null;
  state: string | null;
  email: string | null;
  country: string | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
} | null;

// Source: src/sanity/lib/query.ts
// Variable: CONTACT_US_PAGE_CHAT
// Query: *[_type == 'chatBubble' && defined(slug.current) && slug.current == $page][0]{    messages[]{      _key,      inbound,      outbound    } }
export type CONTACT_US_PAGE_CHAT_RESULT = {
  messages: Array<{
    _key: string;
    inbound: string | null;
    outbound: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/query.ts
// Variable: PAGE_METADATA_QUERY
// Query: *[_type == 'page' && defined(slug.current) && slug.current == $page][0]{  "title": seo.metaTitle,  "description": seo.metaDescription }
export type PAGE_METADATA_QUERY_RESULT = {
  title: string | null;
  description: string | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    "*[_type == 'siteSettings'][0]{\n  navLinks[]{\n    _key,\n    _type,\n    href,\n    label,\n    isButton,\n    isExternal,\n    label,\n    dropdownLinks[]{\n      _key,\n      label,\n      links[]{\n        _key,\n        _type,\n        href,\n        label,\n        isButton,\n        isExternal\n      }\n    }\n  }\n}": NAVIGATION_QUERY_RESULT;
    '*[_type == \'siteSettings\'][0]{\n  "columns": footerColumns[]{\n    _key,\n    title,\n    links[]{\n      _key,\n      href,\n      label\n    }\n  },\n  "text": footerText,\n  "street": contactInfo.street,\n  "zip": contactInfo.zip,\n  "city": contactInfo.city,\n  "state": contactInfo.state,\n  "email": contactInfo.email,\n  "country": contactInfo.country,\n  "socialLinks": socialLinks[]\n}': FOOTER_QUERY_RESULT;
    "*[_type == 'chatBubble'\n && defined(slug.current)\n && slug.current == $page][0]{\n    messages[]{\n      _key,\n      inbound,\n      outbound\n    }\n }": CONTACT_US_PAGE_CHAT_RESULT;
    '*[_type == \'page\'\n && defined(slug.current)\n && slug.current == $page][0]{\n  "title": seo.metaTitle,\n  "description": seo.metaDescription\n }': PAGE_METADATA_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
