/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  seo?: Seo;
  navLinks?: Array<
    | ({
        _key: string;
      } & NavLink)
    | ({
        _key: string;
      } & NavDropdown)
  >;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerText?: string;
  contactInfo?: {
    street?: string;
    zip?: string;
    city?: string;
    state?: string;
    email?: string;
    country?: string;
  };
};

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type VideoEmbedded = {
  _type: 'videoEmbedded';
  label?: string;
  videoId?: string;
  caption?: string;
};

export type FooterColumn = {
  _type: 'footerColumn';
  title?: string;
  links?: Array<{
    label?: string;
    href?: string;
    _type: 'link';
    _key: string;
  }>;
};

export type NavDropdown = {
  _type: 'navDropdown';
  label?: string;
  href?: string;
  dropdownLinks?: Array<{
    label?: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: 'dropdownGroup';
    _key: string;
  }>;
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  href?: string;
  isButton?: boolean;
  isExternal?: boolean;
};

export type Faq = {
  _type: 'faq';
  title?: string;
  body?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | Seo
  | VideoEmbedded
  | FooterColumn
  | NavDropdown
  | NavLink
  | Faq
  | SocialLink
  | SanityImageAssetReference
  | ImageWithAlt
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/query.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == 'siteSettings'][0]{  navLinks[]{    _key,    _type,    href,    label,    isButton,    isExternal,    label,    dropdownLinks[]{      _key,      label,      links[]{        _key,        _type,        href,        label,        isButton,        isExternal      }    }  }}
export type NAVIGATION_QUERY_RESULT = {
  navLinks: Array<
    | {
        _key: string;
        _type: 'navDropdown';
        href: string | null;
        label: string | null;
        isButton: null;
        isExternal: null;
        dropdownLinks: Array<{
          _key: string;
          label: string | null;
          links: Array<{
            _key: string;
            _type: 'navLink';
            href: string | null;
            label: string | null;
            isButton: boolean | null;
            isExternal: boolean | null;
          }> | null;
        }> | null;
      }
    | {
        _key: string;
        _type: 'navLink';
        href: string | null;
        label: string | null;
        isButton: boolean | null;
        isExternal: boolean | null;
        dropdownLinks: null;
      }
  > | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    "*[_type == 'siteSettings'][0]{\n  navLinks[]{\n    _key,\n    _type,\n    href,\n    label,\n    isButton,\n    isExternal,\n    label,\n    dropdownLinks[]{\n      _key,\n      label,\n      links[]{\n        _key,\n        _type,\n        href,\n        label,\n        isButton,\n        isExternal\n      }\n    }\n  }\n}": NAVIGATION_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
